name = "Whitehat"
license = "MIT"
licenselink = "https://github.com/jsvensson/whitehat/blob/master/LICENSE"
description = "A port of the Hacker theme for Hexo."
homepage = "https://github.com/jsvensson/whitehat"
tags = []
features = []
min_version = "0.51"

[author]
  name = "Johan Svensson"
  homepage = "https://github.com/jsvensson"

[original]
  name = "Hacker"
  homepage = "https://github.com/CodeDaraW/Hacker"
  repo = "https://github.com/CodeDaraW/Hacker"
